catalog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('books/', BookListView.as_view(), name='books'),
    path('authors/', Authors.as_view(), name='authors'),
    path('author-details/<str:pk>', AuthorDetails.as_view(), name='author-details'),
    path('book/<str:pk>/', BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', ListOfBorrowedBooksByUser.as_view(), name='my-borrowed-books'),
    path('book/<uuid:pk>/renew/', renew_book_librarian2, name='renew-book'),

    path('author/create/', AuthorCreate.as_view(), name='create-author'),
    path('author/<int:pk>/update/', AuthorUpdate.as_view(), name='update-author'),
    path('author/<str:pk>/delete/', AuthorDelete.as_view(), name='delete-author'),
]

locallibrary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db.models import *
import uuid
from datetime import date
# Create your models here.
from django.urls import reverse
from django.contrib.auth.models import User


class Genre(Model):
    name = CharField(max_length=200, help_text="Enter a book genre (e.g. SciFi)")

    def __str__(self):
        return self.name


class Book(Model):
    title = CharField(max_length=200)
    author = ForeignKey('Author', on_delete=SET_NULL, null=True)
    summary = TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = CharField('ISBN', max_length=13, unique=True, help_text='13 Character <a '
                                                                   'href="https://www.isbn-international.org/content'
                                                                   '/what-isbn">ISBN number</a>')
    genre = ManyToManyField(Genre, help_text='Select a genre for this book')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """ Returns url to access a detail record for this book """
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    class Meta:
        ordering = ['title']


class BookInstance(Model):
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    id = UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique id for this book across entire library')
    book = ForeignKey('Book', on_delete=RESTRICT, null=True)
    imprint = CharField(max_length=200)
    borrower = ForeignKey(User, on_delete=SET_NULL, null=True, blank=True)
    due_back = DateField(null=True, blank=True)
    status = CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        # NB: The current user's permissions are stored in a template variable called {{ perms }}
        """
          Check whether the current user has a particular permission using the
          specific variable name associated with the django "app"
          e.g. {{ perms.catalog.can_mark_returned }}
          
          
          Permissions can be tested in a view (FBV) using the permission required decorator
          or in a CBV using PermissionRequiredMixin. See views.py
        """
        permissions = (('can_mark_returned', "Set book as returned"),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(Model):
    first_name = CharField(max_length=100)
    last_name = CharField(max_length=100)
    date_of_birth = DateField(null=True, blank=True)
    date_of_death = DateField('Died', null=True, blank=True)


    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

catalog/forms.py
from django.forms import *
import datetime
from .models import BookInstance


class RenewBookForm(Form):
    renewal_date = DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data.get('renewal_date')

        if data < datetime.date.today():
            raise ValidationError('Invalid date - renewal in past')

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError('Invalid date - renewal more than 4 weeks ahead')

        return data


class RenewBookModelForm(ModelForm):
    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {
            'due_back': 'New renewal date'
        }
        help_texts = {
            'due_back': "Enter a date between now and 4 weeks (default 3)"
        }

    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        if data < datetime.date.today():
            raise ValidationError('Invalid date - renewal in past')

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError('Invalid date - renewal date more than 4 weeks ahead')

        return data

catalog/views.py
import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import *
from django.views.generic.list import ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from .forms import RenewBookModelForm
from .models import *
from django.http import HttpResponseRedirect


class Authors(ListView):
    model = Author
    context_object_name = 'authors'
    template_name = 'catalog/authors.html'
    paginate_by = 2


class AuthorDetails(DetailView):
    model = Author
    context_object_name = 'author'
    template_name = 'catalog/author-details.html'


class AuthorCreate(SuccessMessageMixin, CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/06/2020'}
    template_name = 'catalog/create-update-author.html'
    success_url = reverse_lazy('authors')
    success_message = f' was created successfully'


class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__'
    template_name = 'catalog/create-update-author.html'
    success_url = reverse_lazy('authors')

    def form_valid(self, form):
        messages.success(self.request, "Update successful")
        return super(AuthorUpdate, self).form_valid(form)


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    template_name = 'catalog/delete-author.html'


# Create your views here.
@login_required
@permission_required('catalog.can_mark_returned')
def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()  # all() is implied by default

    return render(request, 'catalog/index.html', {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
    })


class BookListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Book
    # queryset = Book.objects.filter(title__icontains='Harry')[:5]
    template_name = 'catalog/list.html'
    context_object_name = 'book_list'
    paginate_by = 2
    login_url = 'login'
    permission_required = ('catalog.can_mark_returned',)

    # redirect_field_name = None

    # override the queryset method
    def get_queryset(self):
        return Book.objects.all()
        # return Book.objects.filter(title__icontains='kidnap')

    # Overriding the context_data
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['num_of_books'] = Book.objects.count()
        return context

    # def get_permission_denied_message(self):
    #     return redirect(to='/')


class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'
    template_name = 'catalog/book-details.html'


class ListOfBorrowedBooksByUser(LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = 'catalog/borrowed_books.html'
    paginate_by = 2
    context_object_name = 'borrowed'

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


# @login_required
# @permission_required('catalog.can_mark_returned', raise_exception=True)
# def renew_book_librarian(request, pk):
#     book_instance = get_object_or_404(BookInstance, pk=pk)
#     form = RenewBookForm()
#     if request.method == "POST":
#         form = RenewBookForm(request.POST)
#
#         if form.is_valid():
#             book_instance.due_back = form.cleaned_data.get('renewal_date')
#             book_instance.save()
#
#             return HttpResponseRedirect(reverse('my-borrowed-books'))
#
#         else:
#             proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
#             form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})
#
#     return render(request, 'catalog/book_renewal.html', {
#         'form': form,
#         'book_instance': book_instance
#     })


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian2(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
    form = RenewBookModelForm(initial={'due_back': proposed_renewal_date})
    if request.method == "POST":
        form = RenewBookModelForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data.get('due_back')
            book_instance.save()

            return HttpResponseRedirect(reverse('my-borrowed-books'))

        else:
            form = RenewBookModelForm(initial={'due_back': proposed_renewal_date})

    return render(request, 'catalog/book_renewal.html', {
        'form': form,
        'book_instance': book_instance
    })

catalog/templates/catalog/author-details.html
{% extends 'base.html' %}

{% block title %}
{{ author.last_name }} details
{% endblock %}

{% block content %}
    <h1>Details for author <strong>{{ author.first_name }}</strong></h1>
    <hr>
    <h4 class="text-dark">Fullname: {{ author.first_name }} {{ author.last_name }}</h4>
    <h4 class="text-dark">Birthday: {{ author.date_of_birth }}</h4>
    <h4 class="text-dark">Status: {%  if author.date_of_death %}Dead {% else %}Alive{% endif %}</h4>
    <br>
    <a class="btn btn-primary" href="{% url 'update-author' author.id %}">Update Author</a>
    <span><a class="btn btn-danger" href="{% url 'delete-author' author.id %}">Delete Author</a> </span>

{% endblock %}

catalog/templates/catalog/authors.html
{% extends 'base.html' %}

{% block title %}
    Authors
{% endblock %}

{% block content %}
    <h2>Authors</h2>
    <a class="btn btn-success" href="{% url 'create-author' %}">Create Author</a>
    <hr>
    <ul class="list-group">
    {% for author in authors %}
        <li class="list-group-item"><a href="{% url 'author-details' author.id %}" class="text-success">{{ author.first_name }} {{ author.last_name }}</a></li>
    {% endfor %}
    </ul>
    {% block pagination %}
{% if is_paginated %}
<div class="pagination">
<span class="page-links">
   {% if page_obj.has_previous %}
       <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>

   {% endif %}
</span>
<span class="page-current">
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
</span>
{% if page_obj.has_next %}
    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
{% endif %}
</div>
{% endif %}
{% endblock %}
{% endblock %}

catalog/templates/catalog/book-details.html
{% extends 'base.html' %}
{% block title %}
{{ book.title }} details
{% endblock %}

{% block content %}
    <p><strong>Author: </strong><a href="">{{ book.author }}</a></p>
    <p><strong>Summary: </strong>{{ book.summary }}</p>
    <p><strong>ISBN: </strong>{{ book.isbn }}</p>
{#    <p><strong>Language: </strong>{{ book.la }}</p>#}
    <p><strong>Genre: </strong>{{ book.genre.all|join:", " }}</p>

    <div style="margin-left: 20px;margin-top: 20px;">
    <h4>Copies: {{ book.bookinstance_set.all.count }}</h4>
    {% for copy in book.bookinstance_set.all %}
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm'%}text-danger{% else %}text-warning{% endif %}">
           {{ copy.get_status_display }}
        {% comment %}
               NOTE: get_status_display function isn't declared anywhere else in the code.
                This method is auto created cause BookInstance.status is a choices field.
                Django auto creates a method get_FOO_display() for every choices field 'FOO' in a model,
                which can be used to get the current value of the field.
        {% endcomment %}

        </p>
        {% if copy.status != 'a' %}
            <p><strong>Due to be returned: </strong>{{ copy.due_back }}</p>

        {% endif %}
        <p><strong>Imprint: </strong>{{ copy.imprint }}</p>
        <p class="text-muted"><strong>Id: </strong>{{ copy.id }}</p>
    {% endfor %}



    </div>
{% endblock %}

catalog/templates/catalog/book_renewal.html
{% extends 'base.html' %}

{% block title %}
    Renew a book
{% endblock %}
{% block content %}
    <h1>Renew: {{ book_instance.book.title }}</h1>
    <p>Borrower: {{ book_instance.borrower }}</p>
    <p {% if book_instance.is_overdue %}class="text-danger"{% endif %}>Due date:{{ book_instance.due_back }}</p>

    <form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    </form>

    {% if perms.catalog.can_mark_returned %}
        <a href="{% url 'renew-book' book_instance.id %}">Renew</a>

    {% endif %}
{% endblock %}

catalog/templates/catalog/borrowed_books.html
{% extends 'base.html' %}

{% block title %}
    Borrowed books
{% endblock %}

{% block content %}
    <h1>Borrowed books</h1>
    <ul>
    {% for bookinst in borrowed %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.id %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
        </li>

        {% if bookinst.is_overdue %}
        {% if perms.catalog.can_mark_returned %}
        <a class="text-success" href="{% url 'renew-book' bookinst.id %}">Renew {{ bookinst.book.title }}</a>
            {% else %}
            <h2>Not allowed to renew this book</h2>
        {% endif %}
        {% else %}
        <h2>Remember to return the book in good time</h2>
    {% endif %}
         {% empty %}
        <p>There are no books borrowed</p>
    {% endfor %}

    <br>

    </ul>
{% endblock %}

catalog/templates/catalog/create-update-author.html
{% extends 'base.html' %}

{% block title %}
    Create Author
{% endblock %}

{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    <table class="table table-dark table-striped">
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    </form>
{% endblock %}

catalog/templates/catalog/delete-author.html
{% extends 'base.html' %}

{% block title %}
    Delete Author
{% endblock %}

{% block content %}
    <h1>Delete Author</h1>

    <p>Are you sure you want to delete the author: {{ author }}?</p>

    <form action="" method="post">
    {% csrf_token %}
        <a class="btn btn-primary" href="{% url 'index' %}">Go Back</a>
        <span><input type="submit" value="Yes, delete"></span>
    </form>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'base.html' %}
{% block title %}
    Local Library
{% endblock %}

{% block content %}
    {{ request.user.is_authenticated }}
    <h1>Local Library Home</h1>
    <p>Welcome to LocalLibrary, a website developed by <em>Peter Thua</em></p>

    <p>Library Records: </p>
    <ul>
    <li><strong>Books: </strong>{{ num_books }}</li>
    <li><strong>Copies: </strong>{{ num_instances }}</li>
    <li><strong>Copies available: </strong>{{ num_instances_available }}</li>
    <li><strong>Authors: </strong>{{ num_authors }}</li>
    </ul>
{% endblock %}

catalog/templates/catalog/list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Bok List</h1>
    <ul>
        {% for book in book_list %}
    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a><i> by {{ book.author }}</i><br>
    {% empty %}
    <h2>No Such book</h2>
{% endfor %}
    </ul>
    {% block pagination %}
{% if is_paginated %}
<div class="pagination">
<span class="page-links">
   {% if page_obj.has_previous %}
       <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>

   {% endif %}
</span>
<span class="page-current">
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
</span>
{% if page_obj.has_next %}
    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
{% endif %}
</div>
{% endif %}
{% endblock %}
{% endblock %}


{#<h4>{{ num_of_books }}</h4>#}